services:
  postgres:
    container_name: aula_autenticacao_criptografia
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5437:5432